#!/usr/bin/env python
#-*-- coding: utf-8 -*-
import argparse

from BioTab.xlsx2tab import xlsx2tab

SUB_XLSX2TAB = "xslx2tab"

class bistep:
    def __init__(self):
        pass
    def xlsx2tab(self, options):
        x2t = xlsx2tab()
        x2t.output_tab(options)

if __name__ == '__main__':
    biotab = xlsx2tab()
    ## description - Text to display before the argument help (default: none)
    parser=argparse.ArgumentParser(description='biotab: the Swiss army knife of tabular data in bioinformatics') 
    subparsers = parser.add_subparsers(help='sub-command help', dest = 'command')
    #### create the parser for the subcommand ######
    parser_xlsx2tab = subparsers.add_parser(SUB_XLSX2TAB, help='Convert XLSX file to tab-deletmited file.')
    parser_xlsx2tab.add_argument('-i', '--input', metavar='input', \
                      # metavar - A name for the argument in usage messages.
                      help='Input file', required=True)
    parser_xlsx2tab.add_argument('-p', '--prefix', metavar='prefix', help='Prefix of the tab-delemited')
  
 
    ### ###
    parser_tab2xlsx = subparsers.add_parser('tab2xlsx', help='Convert tab-delemited file to XLSX file.')
    parser_tab2xlsx.add_argument('-i', '--input', metavar='input', help='Tab-delemited files. [tab1.txt, tab2.txt]', required=True)
    parser_tab2xlsx.add_argument('-l', '--label', metavar='label', help='Label for the sheets. By default: if this parameter is not given, the file names of tab-delemited files will be used here.')
    options = parser.parse_args()
    dict_cmd = vars(options)
    print "Sub command is: " + dict_cmd['command']
    bt = biotab()
    if dict_cmd['command'] == SUB_XLSX2TAB:
        bt.xlsx2tab(options)
